In [2]:
from sklearn import datasets
digits = datasets.load_digits()

In [6]:
import numpy as np
X = digits.data
y = digits.target

In [4]:
from sklearn.model_selection import train_test_split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.4)

When using K-Fold CV, if K = len(data), then this method is known as Leave-One-Out, usually K = 3, but when we have very less amount of data, we will use Leave-One-Out to maximize the training.

In [19]:
from sklearn.model_selection import KFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
kf = KFold(n_splits=3)
for train, test in kf.split(X):
    print(train) # train and test is a set of index 
    print(train.shape)
    print(test.shape)
    X_train = X[train]
    X_test = X[test]
    y_train = y[train]
    y_test = y[test]
    
    clf = RandomForestClassifier()
    clf.fit(X_train, y_train)
    predicted = clf.predict(X_test)
    print(accuracy_score(y_test, predicted))
    print(confusion_matrix(y_test, predicted))

[ 599  600  601 ..., 1794 1795 1796]
(1198,)
(599,)
0.868113522538
[[63  0  0  0  0  0  0  0  0  0]
 [ 0 56  0  0  0  0  1  0  0  3]
 [ 0  0 49  0  0  0  0  0 12  0]
 [ 0  0  1 58  0  1  0  0  0  1]
 [ 0 10  0  0 45  0  1  0  1  0]
 [ 0  1  0  1  0 55  0  0  1  3]
 [ 0  2  0  0  1  2 53  0  2  0]
 [ 7  0  0  1  3  0  0 46  1  1]
 [ 0  3  0  3  0  0  0  0 51  1]
 [ 1  1  1  2  0  0  0  3  7 44]]
[   0    1    2 ..., 1794 1795 1796]
(1198,)
(599,)
0.921535893155
[[55  0  0  0  1  0  0  0  0  0]
 [ 0 58  0  0  0  0  0  0  1  1]
 [ 0  1 54  0  0  0  0  0  1  0]
 [ 0  0  0 57  0  1  0  1  1  0]
 [ 0  0  0  0 60  0  0  1  0  1]
 [ 0  1  0  1  3 56  0  0  0  1]
 [ 1  0  0  0  0  1 58  0  0  0]
 [ 0  0  0  0  2  0  0 56  1  0]
 [ 1  4  1  1  0  1  1  1 51  0]
 [ 1  4  0  2  1  4  1  1  2 47]]
[   0    1    2 ..., 1195 1196 1197]
(1198,)
(599,)
0.881469115192
[[58  0  0  0  1  0  0  0  0  0]
 [ 0 53  0  3  0  1  0  0  0  5]
 [ 1  0 53  2  0  0  0  0  0  4]
 [ 0  3  1 51  0  2  1  2  1  1]
 [ 4 

In [17]:
# NOTE: some shorcut hack to get list of element from a np array 
# You can't do this is normal Python
a = np.array([1, 3, 4, 5])
a[[0,3]]

array([1, 5])